title: Rust and everything. Hi, I'm Maria Dubyaga
description: > # this means to ignore newlines until "baseurl:"
  This website explores modern technologies like Rust, Kubernetes, and dbt, focusing on building scalable and efficient cloud-native applications. 
  We also will look at the data visualization and reporting with tools like Apache Supersets.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Maria Dubyaga
author-img: maria-dubyaga.png
about-author: I am a software engineer focusing on Rust, Kubernetes, AWS, DBT, Superset.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kraftaa
social-linkedin: maria-dubyaga-4aa1a73
social-email: kraftaa@gmail.com

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
#  - jekyll-local-diagram
#  - jekyll-mermaid

#mermaid:
#  src: 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
