name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ${{ github.workspace }}

      - name: Check _site contents
        run: |
          echo "Checking if _site exists..."
          if [ -d "_site" ]; then
            echo "_site exists! Listing contents:"
            ls -la _site
          else
            echo "⚠️ _site directory is missing! Jekyll build may have failed."
            exit 1  # Fails the workflow if _site is missing
          fi

      - name: Build the Jekyll site
        run: bundle exec jekyll build --trace
        working-directory: ${{ github.workspace }}

      # Upload Jekyll build output as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./_site
          name: github-pages

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2